### ISSUE TITLE
'Rcpp_precious_remove' not provided by package 'Rcpp'

### ISSUE THREAD

**Issue by juniperlsimonis** [ddalthorp/cbinom#1]
I'm currently getting an error when I attempt to use cbinom functions:

`'Rcpp_precious_remove' not provided by package 'Rcpp'`

I'm following the `test/tests.R`  script. 

Session Info below

![image](https://user-images.githubusercontent.com/23511502/139600063-d8931587-7504-4bf6-8632-076f3f0c1259.png)

```
> sessionInfo()
R version 4.0.5 (2021-03-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cbinom_1.6

loaded via a namespace (and not attached):
[1] compiler_4.0.5 Rcpp_1.0.6 
```

**Comment by ddalthorp** [comment]
Try reinstalling Rcpp.

https://stackoverflow.com/questions/68416435/rcpp-package-doesnt-include-rcpp-precious-remove

**Comment by juniperlsimonis** [comment]
that works, thanks! and thanks for the prompt reply!

i think you can prevent this issue by updating the version number on the imports line in the package description file. it currently only requires Rcpp 0.12.0

**Comment by ddalthorp** [comment]
It's more complicated than strictly the version number. E.g., you already had Rcpp 1.0.6 installed and reinstalling it worked. The issue is that with major upgrades of R, package compatibilities often fall apart, and reinstalling old packages in new R is often required. 

I don't pretend to understand how all pathways work. I just play the game and expect to reinstall a lot of packages whenever R goes through a big step (going to 3.3 was one and going to 4 was another).
